"""Native content compatibility with a test-owned request envelope."""
import json
import os
from pathlib import Path
import subprocess
import unittest

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / 'tests/fixtures/strategic_request'
DRIVER = Path(os.environ.get('STRATEGIC_REQUEST_DRIVER',
                             ROOT / '.build/background-values/strategic-request-driver'))


def request_case(mode):
    case = json.loads((FIXTURES / 'input.json').read_text())
    parameters = case['parameters']
    if mode == 'initial':
        case['campaign'] = None
        case['persisted']['strategic_intent'] = None
        case['persisted']['strategy_metadata'] = None
        parameters['identity']['revision'] = 0
        parameters['request_id'] = 'request-proof:generation:0:1:0:2'
        parameters['signals'] = [dict(question='initial_strategy', facts='none', critical=False)]
    elif mode == 'strategic':
        parameters['signals'][0]['question'] = 'strategy:no_progress:stage-1'
    elif mode == 'idle':
        parameters['include_idle'] = True
    elif mode.startswith('background'):
        parameters['wait_ms'] = 80000
        parameters['preparation'] = dict(execution_day=2, strategic_review=mode == 'background_strategic',
            scope=dict(actors=['object:0'], targets=['object:1', 'enemy:far', 'discarded', 'tile:frontier'],
                       needs=[dict(kind='town', ref='object:1')]))
    return case


@unittest.skipUnless(DRIVER.is_file(), 'build strategic-request-driver')
class StrategicRequestTest(unittest.TestCase):
    def assemble(self, case, expected_exit=0):
        result = subprocess.run([str(DRIVER)], input=json.dumps(case, ensure_ascii=False),
                                text=True, capture_output=True, timeout=15)
        self.assertEqual(result.returncode, expected_exit, result.stderr)
        return json.loads(result.stdout), result.stdout.rstrip('\n')

    def test_complete_wire_matches_pre_refactor_production_requests(self):
        # Goldens were captured from both original caller assembly blocks before
        # replacing them, not generated by buildStrategicRequest.
        for mode in ('initial', 'local', 'strategic', 'idle', 'background_routine', 'background_strategic'):
            with self.subTest(mode=mode):
                request, wire = self.assemble(request_case(mode))
                expected = (FIXTURES / (mode + '.json')).read_text().rstrip('\n')
                self.assertEqual(request, json.loads(expected))
                self.assertEqual(wire, expected)

    def test_local_screening_keeps_full_source_facts_and_mode_specific_evidence(self):
        local, _ = self.assemble(request_case('local'))
        detailed, _ = self.assemble(request_case('strategic'))
        self.assertNotIn('neutral:far', {o['ref'] for o in local['observation']['visible_objects']})
        self.assertIn('neutral:far', {o['ref'] for o in detailed['observation']['visible_objects']})
        for mode in ('background_routine', 'background_strategic'):
            request, _ = self.assemble(request_case(mode))
            self.assertEqual(request['allowed_target_refs'], ['object:1', 'enemy:far'])
            self.assertEqual(request['identity']['day'], 1)
            self.assertEqual(request['execution_day'], 2)
            expected_count = 2 if mode == 'background_strategic' else 1
            self.assertEqual(request['evidence_refs'].count('observation:map_overview'), expected_count)
        self.assertEqual(local['memory']['experience_id'], 'request-proof')
        self.assertEqual(local['observation']['strategy_assignments'],
                         [dict(hero_ref='object:0', role='collector')])

    def test_bounded_wire_retains_required_context_and_removes_orphan_evidence(self):
        case = request_case('strategic')
        case['world']['required_context'] = 'x' * 450000
        # Public overview-only facts are removable; the required context is not.
        case['world']['objects'].extend(dict(ref='artifact:' + str(i), kind='artifact', owner=-1,
            visible=True, position=[50, 50, 0], artifact={'effect': 'данные "' * 160}) for i in range(120))
        request, wire = self.assemble(case)
        self.assertLessEqual(len(wire.encode('utf-8')), 512 * 1024)
        self.assertEqual(request['observation']['required_context'], case['world']['required_context'])
        overview = request['observation']['map_overview']
        self.assertGreater(overview['coverage']['omitted_objects'], 0)
        shown = {o['ref'] for o in overview['objects']}
        labels = {r.removeprefix('target:') for r in request['evidence_refs'] if r.startswith('target:artifact:')}
        self.assertEqual(labels, shown & {'artifact:' + str(i) for i in range(120)})

    def test_required_context_overflow_is_reported_in_both_modes_without_dropping_facts(self):
        for mode in ('local', 'background_routine'):
            with self.subTest(mode=mode):
                case = request_case(mode)
                case['world']['required_context'] = 'ж' * (256 * 1024)
                request, wire = self.assemble(case, expected_exit=2)
                self.assertGreater(len(wire.encode('utf-8')), 512 * 1024)
                self.assertEqual(request['observation']['required_context'], case['world']['required_context'])
                self.assertEqual(request['strategic_intent'], case['persisted']['strategic_intent'])


if __name__ == '__main__':
    unittest.main()
